/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  CustomOption,
} from './components/nvq-editor/nvq-editor';

export namespace Components {
  interface NvqAutocomplete {
    'itemsSource': string;
    'name': string;
    'placeholder': string;
    'remote': boolean;
    'value': string;
    'width': string;
  }
  interface NvqEditor {
    'bounds': HTMLElement | string;
    'customOptions': CustomOption[];
    'format': 'object' | 'html' | 'text';
    'formats': string[];
    'maxLength': number;
    'minLength': number;
    'modules': { [index: string]: Object };
    'placeholder': string;
    'readOnly': boolean;
    'required': boolean;
    'scrollingContainer': HTMLElement | string;
    'strict': boolean;
    'theme': string;
  }
  interface NvqLabel {
    'helpText': string;
    'text': string;
  }
  interface NvqProgressBar {
    'max': number;
    'value': number;
  }
}

declare global {


  interface HTMLNvqAutocompleteElement extends Components.NvqAutocomplete, HTMLStencilElement {}
  var HTMLNvqAutocompleteElement: {
    prototype: HTMLNvqAutocompleteElement;
    new (): HTMLNvqAutocompleteElement;
  };

  interface HTMLNvqEditorElement extends Components.NvqEditor, HTMLStencilElement {}
  var HTMLNvqEditorElement: {
    prototype: HTMLNvqEditorElement;
    new (): HTMLNvqEditorElement;
  };

  interface HTMLNvqLabelElement extends Components.NvqLabel, HTMLStencilElement {}
  var HTMLNvqLabelElement: {
    prototype: HTMLNvqLabelElement;
    new (): HTMLNvqLabelElement;
  };

  interface HTMLNvqProgressBarElement extends Components.NvqProgressBar, HTMLStencilElement {}
  var HTMLNvqProgressBarElement: {
    prototype: HTMLNvqProgressBarElement;
    new (): HTMLNvqProgressBarElement;
  };
  interface HTMLElementTagNameMap {
    'nvq-autocomplete': HTMLNvqAutocompleteElement;
    'nvq-editor': HTMLNvqEditorElement;
    'nvq-label': HTMLNvqLabelElement;
    'nvq-progress-bar': HTMLNvqProgressBarElement;
  }
}

declare namespace LocalJSX {
  interface NvqAutocomplete {
    'itemsSource'?: string;
    'name'?: string;
    'placeholder'?: string;
    'remote'?: boolean;
    'value'?: string;
    'width'?: string;
  }
  interface NvqEditor {
    'bounds'?: HTMLElement | string;
    'customOptions'?: CustomOption[];
    'format'?: 'object' | 'html' | 'text';
    'formats'?: string[];
    'maxLength'?: number;
    'minLength'?: number;
    'modules'?: { [index: string]: Object };
    'onOnContentChanged'?: (event: CustomEvent<any>) => void;
    'onOnEditorCreated'?: (event: CustomEvent<any>) => void;
    'onOnSelectionChanged'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'readOnly'?: boolean;
    'required'?: boolean;
    'scrollingContainer'?: HTMLElement | string;
    'strict'?: boolean;
    'theme'?: string;
  }
  interface NvqLabel {
    'helpText'?: string;
    'text'?: string;
  }
  interface NvqProgressBar {
    'max'?: number;
    'value'?: number;
  }

  interface IntrinsicElements {
    'nvq-autocomplete': NvqAutocomplete;
    'nvq-editor': NvqEditor;
    'nvq-label': NvqLabel;
    'nvq-progress-bar': NvqProgressBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'nvq-autocomplete': LocalJSX.NvqAutocomplete & JSXBase.HTMLAttributes<HTMLNvqAutocompleteElement>;
      'nvq-editor': LocalJSX.NvqEditor & JSXBase.HTMLAttributes<HTMLNvqEditorElement>;
      'nvq-label': LocalJSX.NvqLabel & JSXBase.HTMLAttributes<HTMLNvqLabelElement>;
      'nvq-progress-bar': LocalJSX.NvqProgressBar & JSXBase.HTMLAttributes<HTMLNvqProgressBarElement>;
    }
  }
}


