/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CustomOption } from "./components/nvq-editor/nvq-editor";
export namespace Components {
    interface NvqAutocomplete {
        "itemsSource": string;
        "name": string;
        "placeholder": string;
        "remote": boolean;
        "value": string;
        "width": string;
    }
    interface NvqEditor {
        "bounds": HTMLElement | string;
        "content": string;
        "customOptions": CustomOption[];
        "customToolbarPosition": 'top' | 'bottom';
        "debug": string;
        "format": 'html' | 'text' | 'json';
        "formats": string[];
        "maxLength": number;
        "minLength": number;
        "modules": { [index: string]: Object };
        "placeholder": string;
        "preserveWhitespace": boolean;
        "readOnly": boolean;
        "required": boolean;
        "scrollingContainer": HTMLElement | string;
        "strict": boolean;
        "styles": string;
        "theme": string;
    }
    interface NvqLabel {
        "helpText": string;
        "text": string;
    }
    interface NvqProgressBar {
        "max": number;
        "value": number;
    }
}
declare global {
    interface HTMLNvqAutocompleteElement extends Components.NvqAutocomplete, HTMLStencilElement {
    }
    var HTMLNvqAutocompleteElement: {
        prototype: HTMLNvqAutocompleteElement;
        new (): HTMLNvqAutocompleteElement;
    };
    interface HTMLNvqEditorElement extends Components.NvqEditor, HTMLStencilElement {
    }
    var HTMLNvqEditorElement: {
        prototype: HTMLNvqEditorElement;
        new (): HTMLNvqEditorElement;
    };
    interface HTMLNvqLabelElement extends Components.NvqLabel, HTMLStencilElement {
    }
    var HTMLNvqLabelElement: {
        prototype: HTMLNvqLabelElement;
        new (): HTMLNvqLabelElement;
    };
    interface HTMLNvqProgressBarElement extends Components.NvqProgressBar, HTMLStencilElement {
    }
    var HTMLNvqProgressBarElement: {
        prototype: HTMLNvqProgressBarElement;
        new (): HTMLNvqProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "nvq-autocomplete": HTMLNvqAutocompleteElement;
        "nvq-editor": HTMLNvqEditorElement;
        "nvq-label": HTMLNvqLabelElement;
        "nvq-progress-bar": HTMLNvqProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface NvqAutocomplete {
        "itemsSource"?: string;
        "name"?: string;
        "placeholder"?: string;
        "remote"?: boolean;
        "value"?: string;
        "width"?: string;
    }
    interface NvqEditor {
        "bounds"?: HTMLElement | string;
        "content"?: string;
        "customOptions"?: CustomOption[];
        "customToolbarPosition"?: 'top' | 'bottom';
        "debug"?: string;
        "format"?: 'html' | 'text' | 'json';
        "formats"?: string[];
        "maxLength"?: number;
        "minLength"?: number;
        "modules"?: { [index: string]: Object };
        "onContentChanged"?: (event: CustomEvent<any>) => void;
        "onEditorBlur"?: (event: CustomEvent<{
        editor: any;
        source: string;
    }>) => void;
        "onEditorChange"?: (event: CustomEvent<|   {
                editor: any;
                event: 'text-change';
                content: any;
                text: string;
                html: string;
                delta: any;
                oldDelta: any;
                source: string;
            }
        |   {
                editor: any;
                event: 'selection-change';
                range: any;
                oldRange: any;
                source: string;
            }>) => void;
        "onEditorContentChange"?: (event: CustomEvent<{
        editor: any;
        content: any;
        text: string;
        html: string;
        delta: any;
        oldDelta: any;
        source: string;
    }>) => void;
        "onEditorCreated"?: (event: CustomEvent<any>) => void;
        "onEditorFocus"?: (event: CustomEvent<{
        editor: any;
        source: string;
    }>) => void;
        "onEditorInit"?: (event: CustomEvent<any>) => void;
        "onEditorSelectionChange"?: (event: CustomEvent<{
        editor: any;
        range: any;
        oldRange: any;
        source: string;
    }>) => void;
        "onSelectionChanged"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "preserveWhitespace"?: boolean;
        "readOnly"?: boolean;
        "required"?: boolean;
        "scrollingContainer"?: HTMLElement | string;
        "strict"?: boolean;
        "styles"?: string;
        "theme"?: string;
    }
    interface NvqLabel {
        "helpText"?: string;
        "text"?: string;
    }
    interface NvqProgressBar {
        "max"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "nvq-autocomplete": NvqAutocomplete;
        "nvq-editor": NvqEditor;
        "nvq-label": NvqLabel;
        "nvq-progress-bar": NvqProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nvq-autocomplete": LocalJSX.NvqAutocomplete & JSXBase.HTMLAttributes<HTMLNvqAutocompleteElement>;
            "nvq-editor": LocalJSX.NvqEditor & JSXBase.HTMLAttributes<HTMLNvqEditorElement>;
            "nvq-label": LocalJSX.NvqLabel & JSXBase.HTMLAttributes<HTMLNvqLabelElement>;
            "nvq-progress-bar": LocalJSX.NvqProgressBar & JSXBase.HTMLAttributes<HTMLNvqProgressBarElement>;
        }
    }
}
